Repository flux3dp/beam-studio-web, pull requests merged in 2021-07, with the labels that each got.

#30 create beambox-init implementation
  src/implementations/beamboxInit.ts
Labels: size/XS

#31 Add sentry implemtation
  src/implementations/sentry.ts
Labels: size/S

#32 add missing sentry libs
  package.json
  yarn.lock
Labels: size/M

#33 append hash to both js and css files to avoid browser caching old files
  webpack.common.js
Labels: size/XS

#34 Remove import select.js
  src/externals.ts
  webpack.common.js
Labels: size/XS

#37 Fix svgnest buttons z-indes
  src/assets/scss/components/_svg-nest-buttons.scss
Labels: size/XS

#39 failed e2e test
  cypress/integration/landing.spec.js
Labels: size/XS

#40 Revert "failed e2e test"
  cypress/integration/landing.spec.js
Labels: size/XS

#41 enable auto deployment
  .github/workflows/ready-for-deployment.yml
Labels: size/M

#42 1. add tests 2. add missing svg files
  cypress/integration/landing.spec.js
  cypress/integration/layer-panel.spec.js
  cypress/integration/preference.spec.js
  cypress/support/commands.js
  package.json
  src/assets/images/beambox/spin.svg
  src/assets/images/beambox/start.svg
  yarn.lock
Labels: size/L

#58 fix missing dxf2svg and imagetracer
  src/index.html
  webpack.common.js
Labels: size/XS

#66 fix tests
  .github/workflows/e2e.yml
  cypress/integration/canvas/drawing.spec.ts
  package.json
  yarn.lock
Labels: size/L

#67 specify mac os as running environment
  .github/workflows/ready-for-deployment.yml
Labels: size/XS

#68 1. style the menu icon 2. change baseUrl from ip to domain name 3. add a new e2e test for shortcuts
  cypress.prod.json
  cypress/integration/shortcut.spec.ts
  package.json
  src/assets/scss/vendor/_top-bar-menu-container.scss
Labels: size/S
