Repository flux3dp/beam-studio-web, pull requests merged in 2021-08, with the labels that each got.

#69 add a new hotkey for connection type selection page
  .github/workflows/e2e.yml
  cypress/integration/shortcut.spec.ts
  src/assets/scss/lang/_de.scss
  src/assets/scss/lang/_en.scss
  src/assets/scss/lang/_es.scss
  src/assets/scss/lang/_ja.scss
  src/assets/scss/lang/_zh-cn.scss
  src/assets/scss/lang/_zh-tw.scss
  src/hotkeys.ts
Labels: size/M

#70 modify cypress prod config
  cypress.prod.json
Labels: size/XS

#71 since skipping login is not allowed in web, we have to fix e2e test to simulate the user login scenario
  .github/workflows/e2e.yml
  cypress/integration/canvas/landing.spec.ts
  cypress/support/commands.ts
Labels: size/S

#72 forget to give username and password in post deployment test
  .github/workflows/ready-for-deployment.yml
Labels: size/XS

#73 Update threshold slider style
  src/assets/scss/layout/beambox/right-panel/_object-panel.scss
Labels: size/XS

#74 Update svg nest buttons style
  src/assets/scss/components/_svg-nest-buttons.scss
Labels: size/XS

#76 Add path preview style and src
  src/assets/images/Pause.svg
  src/assets/images/Play.svg
  src/assets/images/Stop.svg
  src/assets/images/print-preview.svg
  src/assets/scss/layout/_beambox-studio.scss
  src/assets/scss/layout/beambox/_path-preview.scss
  src/assets/scss/layout/beambox/_top-bar.scss
Labels: size/L

#75 add e2e test for polygon sides option
  cypress/integration/canvas/drawing.spec.ts
Labels: size/XS

#77 Update path preview style
  src/assets/scss/layout/beambox/_path-preview.scss
Labels: size/S

#78 1. run cypress tests in parallel 2. fix flaky test
  .github/workflows/e2e.yml
  .github/workflows/ready-for-deployment.yml
  cypress.json
  cypress.prod.json
  cypress/integration/canvas/zoom.spec.ts
  package.json
  yarn.lock
Labels: size/L

#79 show popup to avoid unintentional leaving
  src/index.html
  src/index.tsx
Labels: size/XS

#80 upgrade cypress to 8.2.0
  cypress/integration/canvas/drawing.spec.ts
  cypress/integration/shortcut.spec.ts
  package.json
  yarn.lock
Labels: size/S

#81 Fix path preview
  src/assets/images/path-preview.svg
  src/assets/images/print-preview.svg
  src/assets/scss/layout/beambox/_path-preview.scss
  src/assets/scss/layout/beambox/_top-bar.scss
Labels: size/M

#82 Update path preview related style
  src/assets/scss/layout/beambox/_path-preview.scss
  src/assets/scss/layout/beambox/_top-bar.scss
Labels: size/M

#83 in web, should display #801 popup error while doing actions which require device connection
  cypress/integration/top-bar/device-disconnection.spec.ts
Labels: size/S

#84 Update path preview style
  src/assets/scss/layout/beambox/_path-preview.scss
Labels: size/XS

#85 Adjust path preview icon
  src/assets/images/path-preview.svg
  src/assets/scss/layout/beambox/_top-bar.scss
Labels: size/M

#86 Update context menu
  package.json
  src/assets/scss/base/__base.scss
  src/assets/scss/base/_context-menu.scss
  src/assets/scss/layout/beambox/_svg-editor.scss
  src/assets/scss/layout/beambox/_zoom-block.scss
  src/assets/scss/layout/beambox/right-panel/_layer-panel.scss
  src/externals.ts
  yarn.lock
Labels: size/L

#87 Add wait before operating polygon
  cypress/integration/canvas/drawing.spec.ts
Labels: size/XS

#88 Add context menu e2e test
  cypress/integration/canvas/contextmenu.spec.ts
  cypress/support/commands.ts
Labels: size/M

#89 fix css
  src/assets/scss/layout/beambox/right-panel/_layer-panel.scss
  src/assets/scss/layout/beambox/right-panel/_right-panel.scss
Labels: size/XS

#90 Update layer panel style
  src/assets/scss/layout/beambox/right-panel/_layer-panel.scss
Labels: size/XS

#91 Add web common-tools style
  src/assets/scss/layout/beambox/_top-bar.scss
Labels: size/S

#92 Add media tutorial
  src/assets/images/icon-clear.svg
  src/assets/scss/components/__components.scss
  src/assets/scss/components/_media-tutorial.scss
  webpack.common.js
Labels: size/M

#95 Fix webpack
  webpack.common.js
Labels: size/XS

#94 Fix style again
  src/assets/scss/layout/beambox/_path-preview.scss
Labels: size/XS

#96 Add dependencies
  cypress/integration/canvas/landing.spec.ts
  cypress/support/commands.ts
  package.json
  yarn.lock
Labels: size/M
