Repository flux3dp/beam-studio-web, pull requests merged in 2021-09, with the labels that each got.

#97 Fix web style
  src/assets/scss/layout/beambox/_top-bar.scss
  src/assets/scss/layout/beambox/right-panel/_layer-panel.scss
  src/assets/scss/layout/beambox/right-panel/_right-panel.scss
Labels: size/S

#98 Update svgnest import method
  src/externals.ts
  webpack.common.js
Labels: size/S

#99 Add hashchange listener
  src/index.tsx
Labels: size/XS

#100 Support web fonts
  src/implementations/fontHelper.ts
  src/implementations/fonts/fontNameMap.ts
  src/implementations/fonts/fontPreviewSrc.ts
  src/implementations/fonts/googleFonts.ts
  src/implementations/fonts/webFonts.ts
  src/index.html
Labels: size/XXL

#101 Fix and changes for web
  src/assets/images/top-bar/icon-redo.svg
  src/assets/images/top-bar/icon-undo.svg
  src/assets/scss/layout/beambox/_path-preview.scss
  src/assets/scss/layout/beambox/_top-bar.scss
  src/assets/scss/layout/beambox/right-panel/_object-panel.scss
  src/assets/scss/vendor/_top-bar-menu-container.scss
  src/implementations/dialog.ts
Labels: size/M

#102 Update path preview button behavior
  cypress/integration/top-bar/device-disconnection.spec.ts
Labels: size/XS

#104 Add assets
  src/assets/images/touch-drag.svg
  src/assets/images/touch-zoom.svg
  src/assets/video/autofocus.webm
  src/assets/video/bb_focus.webm
  src/assets/video/bm_focus.webm
  src/assets/video/put_paper.webm
  src/assets/video/touch-contextmenu.webm
  src/assets/video/touch-multiselect.webm
  src/assets/video/touch-select.webm
  webpack.common.js
Labels: size/M

#105 Update style and Add image for top bar menu
  src/assets/images/icon-arrow-d.svg
  src/assets/images/logo-line.svg
  src/assets/scss/vendor/_top-bar-menu-container.scss
Labels: size/M

#107 Update e2e tests
  cypress/integration/canvas/contextmenu.spec.ts
  cypress/integration/canvas/drawing.spec.ts
  cypress/integration/canvas/landing.spec.ts
  cypress/integration/canvas/zoom.spec.ts
  cypress/integration/left-panel/drawing-tools.spec.ts
  cypress/integration/preference.spec.ts
  cypress/integration/right-panel/layer-panel.spec.ts
  cypress/integration/shortcut.spec.ts
  cypress/integration/top-bar/device-disconnection.spec.ts
  cypress/support/commands.ts
  src/assets/images/beambox/icon-analyze.svg
  src/assets/scss/vendor/_top-bar-menu-container.scss
Labels: size/L

#108 Add landing test back
  cypress/integration/canvas/landing.spec.ts
Labels: size/M

#109 Feature/cypress
  .eslintrc.json
  cypress/fixtures/flux.png
  cypress/integration/canvas/drawing.spec.ts
  cypress/integration/left-panel/pen-tools.spec.ts
  cypress/integration/left-panel/polygon-tools.spec.ts
  cypress/integration/left-panel/text-tools.spec.ts
  cypress/integration/modify/align-tools.spec.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  package.json
  yarn.lock
Labels: size/L

#110 add test and change landing to landingEditor
  cypress/fixtures/flux.png
  cypress/fixtures/map.jpg
  cypress/integration/canvas/upload.spec.ts
  cypress/integration/left-panel/line-tools.spec.ts
  cypress/integration/left-panel/pen-tools.spec.ts
  cypress/integration/left-panel/polygon-tools.spec.ts
  cypress/integration/left-panel/rectangle-tools.spec.ts
  cypress/integration/left-panel/select-tools.spec.ts
  cypress/integration/left-panel/text-tools.spec.ts
  cypress/integration/modify/align-tools.spec.ts
  cypress/support/commands.ts
Labels: size/M

#111 Update Style
  src/assets/scss/layout/_beambox-studio.scss
  src/assets/scss/pages/_initialize.scss
Labels: size/XS

#112 Feature/cypress/modify group
  cypress/integration/canvas/upload.spec.ts
  cypress/integration/left-panel/pen-tools.spec.ts
  cypress/integration/left-panel/polygon-tools.spec.ts
  cypress/integration/left-panel/select-tools.spec.ts
  cypress/integration/left-panel/text-tools.spec.ts
  cypress/integration/modify/align-tools.spec.ts
  cypress/integration/modify/group-tools.spec.ts
Labels: size/XL

#114 Remove hash change listener
  src/index.tsx
Labels: size/XS

#116 Update styles
  src/assets/scss/lang/_de.scss
  src/assets/scss/lang/_en.scss
  src/assets/scss/lang/_es.scss
  src/assets/scss/lang/_ja.scss
  src/assets/scss/lang/_zh-cn.scss
  src/assets/scss/lang/_zh-tw.scss
  src/assets/scss/layout/beambox/_path-preview.scss
  src/assets/scss/layout/beambox/right-panel/_laser-panel.scss
  src/assets/scss/pages/_initialize.scss
  src/assets/scss/pages/_settings.scss
  src/assets/scss/vendor/_top-bar-menu-container.scss
Labels: size/M

#117 Fix style and add assets
  cypress/integration/left-panel/text-tools.spec.ts
  src/assets/scss/components/_layer-color-config.scss
  src/assets/scss/layout/beambox/right-panel/_laser-panel.scss
  src/assets/scss/layout/beambox/right-panel/_object-panel.scss
  src/assets/scss/pages/_settings.scss
  src/assets/video/autofocus.mp4
  src/assets/video/bb_focus.mp4
  src/assets/video/bm_focus.mp4
  src/assets/video/put_paper.mp4
  src/assets/video/touch-contextmenu.mov
  src/assets/video/touch-multiselect.mov
  src/assets/video/touch-select.mov
Labels: size/S

#118 Fix for web3
  cypress/integration/left-panel/rectangle-tools.spec.ts
  src/assets/scss/components/_about-beam-studio.scss
  src/assets/scss/components/_document-panel.scss
  src/assets/scss/components/_svg-nest-buttons.scss
  src/assets/scss/layout/beambox/right-panel/_object-panel.scss
  src/implementations/changelog.ts
  src/implementations/fontHelper.ts
Labels: size/M

#120 Update e2e test for new init dialog behavior
  cypress/integration/canvas/landing.spec.ts
  cypress/support/commands.ts
Labels: size/S

#121 Accept all file type in pad
  src/implementations/dialog.ts
Labels: size/XS

#122 Block small screen mobile platform
  src/assets/scss/pages/__pages.scss
  src/assets/scss/pages/_error.scss
  src/index.tsx
Labels: size/S
