Repository flux3dp/beam-studio-web, pull requests merged in 2021-06, with the labels that each got.

#9 make Dialog appear as a popup
  src/components/Dialog.tsx
Labels: size/XS

#11 Update FileSaver.js to implement save dialog
  package.json
  src/implementations/dialog.ts
  yarn.lock
Labels: size/L

#12 fix css of management popup
  src/components/Beambox.tsx
Labels: size/L

#14 Add webpack worker loader
  package.json
  webpack.common.js
  yarn.lock
Labels: size/S

#15 build menu prototype
  package.json
  src/App.tsx
  src/assets/scss/alert/_alerts-container.scss
  src/assets/scss/beambox/_beambox-container.scss
  src/assets/scss/beambox/_top-bar-menu-container.scss
  src/assets/scss/dialog/_dialog-container.scss
  src/assets/scss/main.scss
  src/assets/scss/share/_modal-window.scss
  src/components/AlertsAndProgress.tsx
  src/components/Beambox.tsx
  src/components/Dialog.tsx
  src/externals.ts
  src/global.ts
  src/implementations/communicator.ts
  src/implementations/menuEventListenerFactory.ts
  src/index.tsx
  src/main.ts
  webpack.common.js
  yarn.lock
Labels: size/XXL

#16 Update storage to get string and number value
  src/implementations/storage.ts
Labels: size/S

#18 implement menu related code
  src/implementations/customMenuActionProvider.ts
  src/implementations/menu.ts
  src/implementations/recentMenuUpdater.ts
Labels: size/S

#22 Update os & network implementations
  src/implementations/network.ts
  src/implementations/os.ts
Labels: size/M

#25 set version to 'web' in order to identify the platform between web and desktop
  src/externals.ts
  src/global.ts
  src/index.html
  src/index.tsx
Labels: size/M

#26 Add pdfHelper using utils ws
  src/implementations/pdfHelper.ts
Labels: size/S

#27 add emitter to decide if the menu item is disabled or not
  src/implementations/menu.ts
Labels: size/S

#28 Add getFontName to fontHelper
  src/implementations/fontHelper.ts
Labels: size/M

#29 Update menu
  src/implementations/menu.ts
Labels: size/XS
